<?php
/**
 * Collection Summary Report API
 * Only admins can generate this report
 */

require_once dirname(__DIR__, 2) . '/middleware/auth.php';

// Only admins can generate collection summary report
if (!isAdmin()) {
    die('Error: Unauthorized. Only administrators can generate this report.');
}

// Get overall statistics
$feeModel = new Fee();
$studentModel = new Student();
$paymentModel = new Payment();

$feeStats = $feeModel->getStats();
$studentStats = $studentModel->getStats();
$paymentStats = $paymentModel->getStats([]);

// Get collection rate
$collectionRate = $feeStats['total_due'] > 0 ? ($feeStats['total_paid'] / $feeStats['total_due']) * 100 : 0;

// Build report data
$appName = APP_NAME;
$generatedBy = htmlspecialchars($_SESSION['fullname']) . ' (' . ucfirst($_SESSION['role']) . ')';
$generatedOn = date('d/m/Y H:i:s');

// Generate HTML report
$html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Collection Summary Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
            color: #333;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 16px;
            color: #10b981;
        }
        .info {
            margin-bottom: 20px;
        }
        .info-row {
            margin: 5px 0;
        }
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 120px;
        }
        .section {
            margin: 30px 0;
        }
        .section-title {
            font-size: 14px;
            font-weight: bold;
            color: #333;
            margin-bottom: 15px;
            padding-bottom: 5px;
            border-bottom: 2px solid #10b981;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin: 20px 0;
        }
        .stat-box {
            background: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
            border-left: 4px solid #10b981;
        }
        .stat-label {
            font-size: 11px;
            color: #666;
            margin-bottom: 5px;
        }
        .stat-value {
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }
        .stat-value.success {
            color: #10b981;
        }
        .stat-value.danger {
            color: #dc2626;
        }
        .stat-value.warning {
            color: #f59e0b;
        }
        .progress-bar {
            height: 30px;
            background: #e5e7eb;
            border-radius: 5px;
            overflow: hidden;
            margin: 10px 0;
        }
        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #10b981, #059669);
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>' . $appName . '</h1>
        <h2>Overall Collection Summary Report</h2>
    </div>

    <div class="info">
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span>' . $generatedBy . '</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated On:</span>
            <span>' . $generatedOn . '</span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Student Statistics</div>
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-label">Total Students</div>
                <div class="stat-value">' . number_format($studentStats['total'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Active Students</div>
                <div class="stat-value success">' . number_format($studentStats['active'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Students with Fees</div>
                <div class="stat-value">' . number_format($feeStats['total_fees'] ?? 0) . '</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Fee Collection Overview</div>
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-label">Total Fees Assigned</div>
                <div class="stat-value">' . formatCurrency($feeStats['total_due'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Total Collected</div>
                <div class="stat-value success">' . formatCurrency($feeStats['total_paid'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Outstanding Balance</div>
                <div class="stat-value danger">' . formatCurrency($feeStats['total_balance'] ?? 0) . '</div>
            </div>
        </div>

        <div style="margin-top: 20px;">
            <p style="font-weight: bold; margin-bottom: 10px;">Collection Rate:</p>
            <div class="progress-bar">
                <div class="progress-fill" style="width: ' . number_format($collectionRate, 1) . '%">
                    ' . number_format($collectionRate, 1) . '%
                </div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Fee Status Breakdown</div>
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-label">Fully Paid</div>
                <div class="stat-value success">' . number_format($feeStats['paid_count'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Partial Payment</div>
                <div class="stat-value warning">' . number_format($feeStats['partial_count'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Overdue</div>
                <div class="stat-value danger">' . number_format($feeStats['overdue_count'] ?? 0) . '</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Payment Method Breakdown</div>
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-label">Cash Payments</div>
                <div class="stat-value">' . formatCurrency($paymentStats['cash_amount'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Mobile Money</div>
                <div class="stat-value">' . formatCurrency($paymentStats['mobile_money_amount'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Others</div>
                <div class="stat-value">' . formatCurrency($paymentStats['others_amount'] ?? 0) . '</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This is a computer-generated report from ' . $appName . '</p>
        <p>Generated on ' . $generatedOn . '</p>
    </div>
</body>
</html>';

// Generate PDF
$tempHtml = tempnam(sys_get_temp_dir(), 'report_') . '.html';
$pdfFile = tempnam(sys_get_temp_dir(), 'report_') . '.pdf';

file_put_contents($tempHtml, $html);

$command = "wkhtmltopdf --page-size A4 --orientation Portrait --margin-top 10mm --margin-bottom 10mm --margin-left 10mm --margin-right 10mm " . escapeshellarg($tempHtml) . " " . escapeshellarg($pdfFile) . " 2>&1";
exec($command, $output, $returnCode);

// Clean up HTML file
unlink($tempHtml);

if ($returnCode !== 0 || !file_exists($pdfFile)) {
    error_log("PDF generation failed: " . implode("\n", $output));
    die('Error: Failed to generate PDF report');
}

// Output PDF
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="collection_summary_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . filesize($pdfFile));
readfile($pdfFile);

// Clean up PDF file
unlink($pdfFile);
exit;
