<?php
/**
 * Outstanding Fees Report API
 * Only admins can generate this report
 */

require_once dirname(__DIR__, 2) . '/middleware/auth.php';

// Only admins can generate outstanding fees report
if (!isAdmin()) {
    die('Error: Unauthorized. Only administrators can generate this report.');
}

// Get parameters
$classFilter = $_GET['class'] ?? '';

// Get outstanding fees
$feeModel = new Fee();
$fees = $feeModel->getAll();

// Filter by class if specified
if (!empty($classFilter)) {
    $fees = array_filter($fees, function($fee) use ($classFilter) {
        return $fee['class'] === $classFilter && $fee['balance'] > 0;
    });
} else {
    $fees = array_filter($fees, function($fee) {
        return $fee['balance'] > 0;
    });
}

// Calculate totals
$totalDue = 0;
$totalPaid = 0;
$totalBalance = 0;
$studentCount = count($fees);

foreach ($fees as $fee) {
    $totalDue += $fee['amount_due'];
    $totalPaid += $fee['amount_paid'];
    $totalBalance += $fee['balance'];
}

// Build report data
$appName = APP_NAME;
$classFilterText = !empty($classFilter) ? htmlspecialchars($classFilter) : 'All Classes';
$generatedBy = htmlspecialchars($_SESSION['fullname']) . ' (' . ucfirst($_SESSION['role']) . ')';
$generatedOn = date('d/m/Y H:i:s');

// Generate HTML report
$html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Outstanding Fees Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
            color: #333;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 16px;
            color: #dc2626;
        }
        .info {
            margin-bottom: 20px;
        }
        .info-row {
            margin: 5px 0;
        }
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 120px;
        }
        .summary {
            background: #fef2f2;
            padding: 15px;
            margin: 20px 0;
            border-radius: 5px;
            border-left: 4px solid #dc2626;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
        }
        .summary-item {
            text-align: center;
        }
        .summary-label {
            font-size: 11px;
            color: #666;
            margin-bottom: 5px;
        }
        .summary-value {
            font-size: 16px;
            font-weight: bold;
            color: #dc2626;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #dc2626;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .overdue {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>' . $appName . '</h1>
        <h2>Outstanding Fees Report</h2>
    </div>

    <div class="info">
        <div class="info-row">
            <span class="info-label">Class Filter:</span>
            <span>' . $classFilterText . '</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span>' . $generatedBy . '</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated On:</span>
            <span>' . $generatedOn . '</span>
        </div>
    </div>

    <div class="summary">
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-label">Students with Balance</div>
                <div class="summary-value">' . number_format($studentCount) . '</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Total Fees Due</div>
                <div class="summary-value">' . formatCurrency($totalDue) . '</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Total Paid</div>
                <div class="summary-value" style="color: #10b981;">' . formatCurrency($totalPaid) . '</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Outstanding Balance</div>
                <div class="summary-value">' . formatCurrency($totalBalance) . '</div>
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Class</th>
                <th>Amount Due</th>
                <th>Amount Paid</th>
                <th>Balance</th>
                <th>Due Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>';

if (empty($fees)) {
    $html .= '<tr><td colspan="8" style="text-align: center; padding: 20px;">No outstanding fees found</td></tr>';
} else {
    foreach ($fees as $fee) {
        $isOverdue = strtotime($fee['due_date']) < time();
        $html .= '<tr>';
        $html .= '<td>' . htmlspecialchars($fee['student_id']) . '</td>';
        $html .= '<td>' . htmlspecialchars($fee['first_name'] . ' ' . $fee['last_name']) . '</td>';
        $html .= '<td>' . htmlspecialchars($fee['class']) . '</td>';
        $html .= '<td class="text-right">' . formatCurrency($fee['amount_due']) . '</td>';
        $html .= '<td class="text-right">' . formatCurrency($fee['amount_paid']) . '</td>';
        $html .= '<td class="text-right"><strong class="overdue">' . formatCurrency($fee['balance']) . '</strong></td>';
        $html .= '<td>' . formatDate($fee['due_date']) . '</td>';
        $html .= '<td>' . ($isOverdue ? '<span class="overdue">OVERDUE</span>' : 'Pending') . '</td>';
        $html .= '</tr>';
    }
}

$html .= '</tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated report from ' . $appName . '</p>
        <p>Generated on ' . $generatedOn . '</p>
    </div>
</body>
</html>';

// Generate PDF
$tempHtml = tempnam(sys_get_temp_dir(), 'report_') . '.html';
$pdfFile = tempnam(sys_get_temp_dir(), 'report_') . '.pdf';

file_put_contents($tempHtml, $html);

$command = "wkhtmltopdf --page-size A4 --orientation Landscape --margin-top 10mm --margin-bottom 10mm --margin-left 10mm --margin-right 10mm " . escapeshellarg($tempHtml) . " " . escapeshellarg($pdfFile) . " 2>&1";
exec($command, $output, $returnCode);

// Clean up HTML file
unlink($tempHtml);

if ($returnCode !== 0 || !file_exists($pdfFile)) {
    error_log("PDF generation failed: " . implode("\n", $output));
    die('Error: Failed to generate PDF report');
}

// Output PDF
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="outstanding_fees_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . filesize($pdfFile));
readfile($pdfFile);

// Clean up PDF file
unlink($pdfFile);
exit;
