<?php
/**
 * Payment Summary Report API
 */

require_once dirname(__DIR__, 2) . '/middleware/auth.php';

// Get parameters
$dateFrom = $_GET['date_from'] ?? '';
$dateTo = $_GET['date_to'] ?? '';

// Validate dates
if (empty($dateFrom) || empty($dateTo)) {
    die('Error: Date range is required');
}

// Get payment data based on role
$paymentModel = new Payment();
$filters = [
    'date_from' => $dateFrom,
    'date_to' => $dateTo
];

// Teachers can only see their own collections
if (!isAdmin()) {
    $filters['received_by'] = $_SESSION['user_id'];
}

$payments = $paymentModel->getAll($filters);
$stats = $paymentModel->getStats($filters);

// Build report data
$appName = APP_NAME;
$reportPeriod = date('d/m/Y', strtotime($dateFrom)) . ' - ' . date('d/m/Y', strtotime($dateTo));
$generatedBy = htmlspecialchars($_SESSION['fullname']) . ' (' . ucfirst($_SESSION['role']) . ')';
$generatedOn = date('d/m/Y H:i:s');

$totalPayments = number_format($stats['total_payments'] ?? 0);
$totalAmount = formatCurrency($stats['total_amount'] ?? 0);
$cashAmount = formatCurrency($stats['cash_amount'] ?? 0);
$mobileMoneyAmount = formatCurrency($stats['mobile_money_amount'] ?? 0);
$othersAmount = formatCurrency($stats['others_amount'] ?? 0);
$avgPayment = formatCurrency($stats['total_payments'] > 0 ? $stats['total_amount'] / $stats['total_payments'] : 0);

// Generate HTML report
$html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Payment Summary Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 20px; color: #333; }
        .header h2 { margin: 5px 0; font-size: 16px; color: #666; }
        .info { margin-bottom: 20px; }
        .info-row { margin: 5px 0; }
        .info-label { font-weight: bold; display: inline-block; width: 120px; }
        .summary { background: #f5f5f5; padding: 15px; margin: 20px 0; border-radius: 5px; }
        .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; }
        .summary-item { text-align: center; }
        .summary-label { font-size: 11px; color: #666; margin-bottom: 5px; }
        .summary-value { font-size: 16px; font-weight: bold; color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #4f46e5; color: white; padding: 10px; text-align: left; font-size: 11px; }
        td { padding: 8px; border-bottom: 1px solid #ddd; font-size: 11px; }
        tr:nth-child(even) { background: #f9f9f9; }
        .text-right { text-align: right; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; text-align: center; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>' . $appName . '</h1>
        <h2>Payment Summary Report</h2>
    </div>
    <div class="info">
        <div class="info-row"><span class="info-label">Report Period:</span><span>' . $reportPeriod . '</span></div>
        <div class="info-row"><span class="info-label">Generated By:</span><span>' . $generatedBy . '</span></div>
        <div class="info-row"><span class="info-label">Generated On:</span><span>' . $generatedOn . '</span></div>
    </div>
    <div class="summary">
        <div class="summary-grid">
            <div class="summary-item"><div class="summary-label">Total Payments</div><div class="summary-value">' . $totalPayments . '</div></div>
            <div class="summary-item"><div class="summary-label">Total Amount</div><div class="summary-value">' . $totalAmount . '</div></div>
            <div class="summary-item"><div class="summary-label">Cash</div><div class="summary-value">' . $cashAmount . '</div></div>
        </div>
        <div class="summary-grid" style="margin-top: 15px;">
            <div class="summary-item"><div class="summary-label">Mobile Money</div><div class="summary-value">' . $mobileMoneyAmount . '</div></div>
            <div class="summary-item"><div class="summary-label">Others</div><div class="summary-value">' . $othersAmount . '</div></div>
            <div class="summary-item"><div class="summary-label">Average Payment</div><div class="summary-value">' . $avgPayment . '</div></div>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Receipt No.</th>
                <th>Student</th>
                <th>Class</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Received By</th>
            </tr>
        </thead>
        <tbody>';

if (empty($payments)) {
    $html .= '<tr><td colspan="7" style="text-align: center; padding: 20px;">No payments found for the selected period</td></tr>';
} else {
    foreach ($payments as $payment) {
        $html .= '<tr>';
        $html .= '<td>' . formatDate($payment['payment_date']) . '</td>';
        $html .= '<td>' . htmlspecialchars($payment['receipt_number']) . '</td>';
        $html .= '<td>' . htmlspecialchars($payment['first_name'] . ' ' . $payment['last_name']) . '</td>';
        $html .= '<td>' . htmlspecialchars($payment['class']) . '</td>';
        $html .= '<td class="text-right"><strong>' . formatCurrency($payment['amount_paid']) . '</strong></td>';
        $html .= '<td>' . ucfirst(str_replace('_', ' ', $payment['payment_method'])) . '</td>';
        $html .= '<td>' . htmlspecialchars($payment['received_by_name']) . '</td>';
        $html .= '</tr>';
    }
}

$html .= '</tbody>
    </table>
    <div class="footer">
        <p>This is a computer-generated report from ' . $appName . '</p>
        <p>Generated on ' . $generatedOn . '</p>
    </div>
</body>
</html>';

// Generate PDF
$tempHtml = tempnam(sys_get_temp_dir(), 'report_') . '.html';
$pdfFile = tempnam(sys_get_temp_dir(), 'report_') . '.pdf';

file_put_contents($tempHtml, $html);

$command = "wkhtmltopdf --page-size A4 --orientation Landscape --margin-top 10mm --margin-bottom 10mm --margin-left 10mm --margin-right 10mm " . escapeshellarg($tempHtml) . " " . escapeshellarg($pdfFile) . " 2>&1";
exec($command, $output, $returnCode);

// Clean up HTML file
unlink($tempHtml);

if ($returnCode !== 0 || !file_exists($pdfFile)) {
    error_log("PDF generation failed: " . implode("\n", $output));
    die('Error: Failed to generate PDF report');
}

// Output PDF
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="payment_summary_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . filesize($pdfFile));
readfile($pdfFile);

// Clean up PDF file
unlink($pdfFile);
exit;
