<?php
/**
 * Student Statistics Report API
 * Only admins can generate this report
 */

require_once dirname(__DIR__, 2) . '/middleware/auth.php';

// Only admins can generate student statistics report
if (!isAdmin()) {
    die('Error: Unauthorized. Only administrators can generate this report.');
}

// Get student statistics
$studentModel = new Student();
$db = new Database();

$studentStats = $studentModel->getStats();

// Get students by class
$db->query("SELECT class, COUNT(*) as count
            FROM students
            WHERE is_active = 1
            GROUP BY class
            ORDER BY class");
$classCounts = $db->fetchAll();

// Get students by gender
$db->query("SELECT gender, COUNT(*) as count
            FROM students
            WHERE is_active = 1
            GROUP BY gender");
$genderCounts = $db->fetchAll();

// Get students by house
$db->query("SELECT house, COUNT(*) as count
            FROM students
            WHERE is_active = 1
            GROUP BY house
            ORDER BY house");
$houseCounts = $db->fetchAll();

// Build report data
$appName = APP_NAME;
$generatedBy = htmlspecialchars($_SESSION['fullname']) . ' (' . ucfirst($_SESSION['role']) . ')';
$generatedOn = date('d/m/Y H:i:s');

// Generate HTML report
$html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Student Statistics Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
            color: #333;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 16px;
            color: #3b82f6;
        }
        .info {
            margin-bottom: 20px;
        }
        .info-row {
            margin: 5px 0;
        }
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 120px;
        }
        .section {
            margin: 30px 0;
        }
        .section-title {
            font-size: 14px;
            font-weight: bold;
            color: #333;
            margin-bottom: 15px;
            padding-bottom: 5px;
            border-bottom: 2px solid #3b82f6;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin: 20px 0;
        }
        .stat-box {
            background: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
            border-left: 4px solid #3b82f6;
        }
        .stat-label {
            font-size: 11px;
            color: #666;
            margin-bottom: 5px;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #3b82f6;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .text-center {
            text-align: center;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>' . $appName . '</h1>
        <h2>Student Statistics Report</h2>
    </div>

    <div class="info">
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span>' . $generatedBy . '</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated On:</span>
            <span>' . $generatedOn . '</span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Overall Student Statistics</div>
        <div class="stats-grid">
            <div class="stat-box">
                <div class="stat-label">Total Students</div>
                <div class="stat-value">' . number_format($studentStats['total'] ?? 0) . '</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Active Students</div>
                <div class="stat-value">' . number_format($studentStats['active'] ?? 0) . '</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Gender Distribution</div>
        <table>
            <thead>
                <tr>
                    <th>Gender</th>
                    <th class="text-center">Count</th>
                    <th class="text-center">Percentage</th>
                </tr>
            </thead>
            <tbody>';

$total = $studentStats['active'] ?? 1;
foreach ($genderCounts as $row) {
    $percentage = ($row['count'] / $total) * 100;
    $html .= '<tr>';
    $html .= '<td>' . ucfirst($row['gender']) . '</td>';
    $html .= '<td class="text-center"><strong>' . number_format($row['count']) . '</strong></td>';
    $html .= '<td class="text-center">' . number_format($percentage, 1) . '%</td>';
    $html .= '</tr>';
}

$html .= '            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Distribution by Class</div>
        <table>
            <thead>
                <tr>
                    <th>Class</th>
                    <th class="text-center">Student Count</th>
                    <th class="text-center">Percentage</th>
                </tr>
            </thead>
            <tbody>';

foreach ($classCounts as $row) {
    $percentage = ($row['count'] / $total) * 100;
    $html .= '<tr>';
    $html .= '<td>' . htmlspecialchars($row['class']) . '</td>';
    $html .= '<td class="text-center"><strong>' . number_format($row['count']) . '</strong></td>';
    $html .= '<td class="text-center">' . number_format($percentage, 1) . '%</td>';
    $html .= '</tr>';
}

$html .= '            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Distribution by House</div>
        <table>
            <thead>
                <tr>
                    <th>House</th>
                    <th class="text-center">Student Count</th>
                    <th class="text-center">Percentage</th>
                </tr>
            </thead>
            <tbody>';

foreach ($houseCounts as $row) {
    $percentage = ($row['count'] / $total) * 100;
    $html .= '<tr>';
    $html .= '<td>House ' . htmlspecialchars($row['house']) . '</td>';
    $html .= '<td class="text-center"><strong>' . number_format($row['count']) . '</strong></td>';
    $html .= '<td class="text-center">' . number_format($percentage, 1) . '%</td>';
    $html .= '</tr>';
}

$html .= '            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This is a computer-generated report from ' . $appName . '</p>
        <p>Generated on ' . $generatedOn . '</p>
    </div>
</body>
</html>';

// Generate PDF
$tempHtml = tempnam(sys_get_temp_dir(), 'report_') . '.html';
$pdfFile = tempnam(sys_get_temp_dir(), 'report_') . '.pdf';

file_put_contents($tempHtml, $html);

$command = "wkhtmltopdf --page-size A4 --orientation Portrait --margin-top 10mm --margin-bottom 10mm --margin-left 10mm --margin-right 10mm " . escapeshellarg($tempHtml) . " " . escapeshellarg($pdfFile) . " 2>&1";
exec($command, $output, $returnCode);

// Clean up HTML file
unlink($tempHtml);

if ($returnCode !== 0 || !file_exists($pdfFile)) {
    error_log("PDF generation failed: " . implode("\n", $output));
    die('Error: Failed to generate PDF report');
}

// Output PDF
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="student_statistics_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . filesize($pdfFile));
readfile($pdfFile);

// Clean up PDF file
unlink($pdfFile);
exit;
